### ISSUE TITLE
Upgrade to 2.17 gives error

### ISSUE THREAD

**Issue by jhagberg** [matthewwolak/nadiv#27]
Using this lib via OptiSel

Upgrading to 2.17.0 gives this warning loading the Pedigree

```
Warning messages:
1: In nPed_fixed[] <- numPed(ped_fixed_ord, check = FALSE) :
  number of items to replace is not a multiple of replacement length
2: In nPed_fixed[] <- numPed(ped_fixed_ord, check = FALSE) :
  number of items to replace is not a multiple of replacement length
```

**Comment by matthewwolak** [comment]
@jhagberg Could you let me know what code you ran that produced this Warning so I can start to trace down the issue?

**Comment by jhagberg** [comment]
Hej
Thanks we are a bit confused where is the 2.17 release. We just find that version on cran bit not here. 
We run this.

`Pedi <- optiSel::prePed(rabbits)`

https://github.com/NBISweden/theherdbook/blob/fb60c18c12cdcdfcbf6137b9daf43921de9bf5ae/R/api.R#L70

I can see if we can make a small test data to replicate the error. But this worked before without warning on version 2.16.

**Comment by matthewwolak** [comment]
Hi,

I apologize, I was a few days behind updating my `master` branch on GitHub. The source that was submitted to CRAN was from the `devel` branch. The 2.17.0 source is currently available both on [CRAN](https://cran.r-project.org/web/packages/nadiv/index.html) and at the `master` [branch repository](https://github.com/matthewwolak/nadiv/tree/master).

Is it possible to send me the `rabbits` data or somehow make it easy for me to access so that I can use this to track down the problem in `nadiv::prepPed()`?

**Comment by matthewwolak** [comment]
@jhagberg I think I tracked down the problem, does the `rabbits` data have >3 columns?

I've made the following change (commit 7ded8b0041c09d2c1a2b0666bd229f4f3faa0d8c) which should allow for more general cases to work without throwing the error like you first reported.

Note, the commit above was made to the `devel` branch, which represents the current state of nadiv (right now this is v2.17.1). I would suggest installing this branch directly from GitHub using the R package [`devtools`](https://CRAN.R-project.org/package=devtools), specifically:

```{R}
devtools::install_github("matthewwolak/nadiv", ref = "devel")
```

Let me know if this solves your warning.

**Comment by jhagberg** [comment]
Hej Sorry I missed your update. Yes the rabbits have more than 3 columns. I will test this asap!

**Comment by jhagberg** [comment]
Hej did an install and is now running  nadiv_2.17.1 

Still get the 

```
Warning message:
In nPed_fixed[] <- numPed(ped_fixed_ord, check = FALSE) :
  number of items to replace is not a multiple of replacement length
```

**Comment by jhagberg** [comment]
Sorry. I thought I started fresh but I did not. A restart fixed this!

**Comment by matthewwolak** [comment]
Great, thank you for following up with this!
