### ISSUE TITLE
Issue in heritability estimation using nadiv 

### ISSUE THREAD

**Issue by sameerjoshi23** [matthewwolak/nadiv#33]
Hi, I am fairly new to R. I am using your alfalfa dataset to learn about computing heritability. I got this error, could you please tell me why I am getting this error and how to fix this. Thank you.

H2 <- nadiv:::pin(model1, tmp ~ V1 / (V1 + V2))
Error in names(pframe) <- paste("V", seq(1, length(pframe)), sep = "") : 
  'names' attribute [2] must be the same length as the vector [0]

**Comment by matthewwolak** [comment]
Hi,
What did you use to produce the `model1` object?

Under the current version of nadiv (v2.17.1), the `pin()` function only works with output from the `asreml` R package version 3. The currently available version of asreml in R is now version 4 and does not work with the `nadiv::pin()` function.

Instead, asreml provides their `vpredict()` function which accomplishes the same thing as nadiv's `pin()` function.

Alternatively, you can use the free, open source [gremlin](https://cran.r-project.org/web/packages/gremlin/index.html) package (see [gremlin on GitHub](https://github.com/matthewwolak/gremlin). You can do univariate models with the current version of gremlin (though, soon multivariate model capability will be implemented) and use gremlin's `deltaSE()` function to estimate standard errors on linear combinations of variance components (i.e., the delta method used by `nadiv::pin()` and `asreml::vpredict()`).

Thus, the nadiv `pin()` function is deprecated and will be removed from a future version of nadiv.

**Comment by matthewwolak** [comment]
`devel` branch of nadiv now indicates the `pin()` function is deprecated: fe873870c2daa12f4265af2ab16f1096817abac1

**Comment by sameerjoshi23** [comment]
Hi Matthew,

Thanks a lot for your explanation. I used vpredict and it worked.

**Comment by sameerjoshi23** [comment]
Hi Matthew,

Sorry, I have another query, I am learning to estimate BLUEs and BLUPs. I am getting negative values for BLUEs and BLUPs. Could you please tell me how to deal with these negative values. Thanks in advance.

Cheers
Sameer

**Comment by matthewwolak** [comment]
Hi Sameer,
I do not understand, it is perfectly reasonable to expect that both BLUEs and BLUPs contain negative values.

**Comment by sameerjoshi23** [comment]
Hi Matthew,

Thanks a lot for your help. Much appreciated.
